/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const ComputerRoom = (props) =>{
  const { nodes, materials } = useGLTF('models/gamingdesk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_3.geometry}
        material={materials['Material.017']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_4.geometry}
        material={materials['Material.074_0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_51.geometry}
        material={materials['Material.025']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_86.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_87.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_88.geometry}
        material={materials['Material.074_39']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Material_0.geometry}
        material={materials.Material}
        position={[-0.61, -0.006, 1.561]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-3.689, 7.316, 0.26]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011_Material010_0.geometry}
        material={materials['Material.074']}
        position={[-0.859, 1.997, -3.537]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.735, 0.9, 1.573]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_Material009_0.geometry}
        material={materials['Material.025']}
        position={[0.742, 0.512, -2.629]}
        scale={[0.061, 0.063, 0.023]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015_Material016_0.geometry}
        material={materials['Material.074_1']}
        position={[-1.655, 2.241, -4.408]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.894, 0.007, 1.064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020_Material020_0.geometry}
        material={materials['Material.074_2']}
        position={[-0.961, 0.788, -3.634]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.607, 0.739, 0.343]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.IOSHIELD_IOSHIELD_0.geometry}
        material={materials['Material.074_3']}
        position={[-2.597, 2.848, -4.225]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.265, 0.309, 0.318]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MOBOAORUSORANGETRANS_MOBOAORUSORANGETRANS_0.geometry}
        material={materials['Material.074_4']}
        position={[-2.356, 2.877, -4.239]}
        rotation={[0, 0, 0.651]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025_Material023_0.geometry}
        material={materials['Material.023']}
        position={[-1.655, 2.241, -4.408]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.894, 0.007, 1.064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026_Material024_0.geometry}
        material={materials['Material.024']}
        position={[-1.655, 2.241, -4.408]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.894, 0.007, 1.064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['metal-mesh-500x500_metal-mesh-500x500_0'].geometry}
        material={materials['Material.074_5']}
        position={[-0.423, 3.57, -3.542]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[1, 1.337, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027_Material008_0.geometry}
        material={materials['Material.074_6']}
        position={[-0.964, 2.71, -4.309]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.015, 0.109, 0.443]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028_Material026_0.geometry}
        material={materials['Material.074_7']}
        position={[-0.957, 2.71, -4.324]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.011, 0.097, 0.444]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube045_Material027_0.geometry}
        material={materials['Material.074_8']}
        position={[-2.121, 0.794, -2.982]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.355, 0.052, 0.206]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['rgb-hdd-cover-aorus-v1_rgb-hdd-cover-aorus-v1_0'].geometry}
        material={materials['Material.074_9']}
        position={[-0.935, 0.832, -2.888]}
        scale={0.369}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['maxresdefault_(1)_maxresdefault_(1)_0'].geometry}
        material={materials['Material.074_10']}
        position={[0.877, 0.836, -3.553]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.394}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_Material028_0.geometry}
        material={materials['Material.074_11']}
        position={[-1.692, 1.144, -0.716]}
        rotation={[-1.571, 1.554, 0]}
        scale={[0.194, 0.194, 0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NVIDIA_LOGO_NVIDIA_LOGO_0.geometry}
        material={materials['Material.074_12']}
        position={[0.006, 0.704, -2.891]}
        scale={0.452}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.psuback_psuback_0.geometry}
        material={materials['Material.074_13']}
        position={[-2.603, 0.78, -3.528]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.595}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.usb_usb_0.geometry}
        material={materials['Material.074_14']}
        position={[0.705, 3.571, -2.897]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.073}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus_Material013_0.geometry}
        material={materials['Material.013']}
        position={[0.699, 3.567, -4.07]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus001_Material032_0.geometry}
        material={materials['Material.032']}
        position={[0.699, 3.567, -4.237]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046_Material034_0.geometry}
        material={materials['Material.034']}
        position={[-1.882, 2.685, -3.682]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.093, 0.424, 0.424]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube048_Material035_0.geometry}
        material={materials['Material.074_15']}
        position={[-1.614, 2.682, -3.682]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.174, 0.394, 0.401]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube049_Material040_0.geometry}
        material={materials['Material.074_16']}
        position={[-1.614, 2.682, -3.682]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.174, 0.394, 0.401]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube051_Material042_0.geometry}
        material={materials['Material.042']}
        position={[-1.614, 2.682, -3.682]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.174, 0.394, 0.401]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005_Material041_0.geometry}
        material={materials['Material.074_17']}
        position={[-1.611, 2.687, -3.69]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.327, 0.327, 0.342]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011_Material045_0.geometry}
        material={materials['Material.045']}
        position={[-1.739, 2.425, -4.217]}
        rotation={[0.474, 0, Math.PI]}
        scale={[0.021, 0.021, 0.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text_Material046_0.geometry}
        material={materials['Material.046']}
        position={[-1.438, 2.502, -3.257]}
        rotation={[0, 0, Math.PI / 2]}
        scale={0.024}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes['test-aorus-m2-souris-aorus-rgb2_test-aorus-m2-souris-aorus-rgb2_0'].geometry
        }
        material={materials['Material.074_18']}
        position={[-1.159, 1.507, -4.352]}
        scale={0.352}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053_Material048_0.geometry}
        material={materials['Material.048']}
        position={[-1.655, 2.241, -4.408]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.894, 0.007, 1.064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube054_Material049_0.geometry}
        material={materials['Material.049']}
        position={[-1.655, 2.241, -4.408]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.894, 0.007, 1.064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055_Material054_0.geometry}
        material={materials['Material.054']}
        position={[-1.223, 1.851, -3.706]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.332, 0.545, 0.132]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube056_Material061_0.geometry}
        material={materials['Material.061']}
        position={[-1.272, 2.001, -3.706]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.281, 0.524, 0.127]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006_Material050_0.geometry}
        material={materials['Material.074_19']}
        position={[-2.095, 1.846, -3.701]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.364, 0.382, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007_Material051_0.geometry}
        material={materials['Material.074_20']}
        position={[-1.244, 1.846, -3.701]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.364, 0.382, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_Material053_0.geometry}
        material={materials['Material.074_21']}
        position={[1.172, 0.256, -0.292]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.244, 1.541, 1.199]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.geforcertx_Material056_0.geometry}
        material={materials['Material.056']}
        position={[-2.293, 2.048, -3.16]}
        scale={[0.104, 0.104, 0.109]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube057_Material059_0.geometry}
        material={materials['Material.074_22']}
        position={[-1.272, 2.001, -3.706]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.281, 0.524, 0.127]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube059_Material058_0.geometry}
        material={materials['Material.058']}
        position={[-1.272, 2.001, -3.706]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.281, 0.524, 0.127]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube060_Material062_0.geometry}
        material={materials['Material.062']}
        position={[-1.237, 2.643, -3.168]}
        scale={[1.333, 0.532, 0.008]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058_Material063_0.geometry}
        material={materials['Material.074_23']}
        position={[-1.226, 2.137, -3.704]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.333, 0.545, 0.008]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.aorus_logotranspa_aorus_logotranspa_0.geometry}
        material={materials['Material.074_24']}
        position={[-1.824, 1.817, -3.158]}
        scale={[0.086, 0.086, 0.091]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube064_Material074_0.geometry}
        material={materials['Material.074_25']}
        position={[1.114, 0.324, -0.274]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[-0.429, 0.429, 0.229]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube067_Material075_0.geometry}
        material={materials['Material.075']}
        position={[1.114, 0.324, -0.274]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[-0.429, 0.429, 0.229]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066_Material076_0.geometry}
        material={materials['Material.076']}
        position={[1.115, 0.323, -0.273]}
        rotation={[Math.PI / 2, -0.011, Math.PI]}
        scale={[-0.429, 0.429, 0.229]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010_Material077_0.geometry}
        material={materials['Material.077']}
        position={[0.772, 0.345, -0.279]}
        rotation={[0, -0.001, 0]}
        scale={[0.119, 0.119, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012_Material082_0.geometry}
        material={materials['Material.082']}
        position={[0.772, 0.345, -0.287]}
        rotation={[0, -0.001, 0]}
        scale={[0.104, 0.104, 0.029]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve001_Material085_0.geometry}
        material={materials['Material.085']}
        position={[-0.577, 1.183, -3.156]}
        rotation={[1.571, -1.234, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube075_Material086_0.geometry}
        material={materials['Material.074_26']}
        position={[-2.58, 1.955, -3.715]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.012, 0.524, 0.177]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve002_Material087_0.geometry}
        material={materials['Material.087']}
        position={[-0.314, 1.838, -4.402]}
        rotation={[1.571, -1.234, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve_Material088_0.geometry}
        material={materials['Material.088']}
        position={[0.73, 2.382, -4.374]}
        rotation={[Math.PI, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube081_Material090_0.geometry}
        material={materials['Material.090']}
        position={[0.932, 0.477, -0.277]}
        rotation={[-1.544, -0.233, 0]}
        scale={[0.026, 0.013, 0.022]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube068_Material092_0.geometry}
        material={materials['Material.092']}
        position={[1.291, 0.445, -0.276]}
        rotation={[-Math.PI / 2, 0.284, 0]}
        scale={[0.06, 0.06, 0.021]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Color-PewDiePie-Logo_Color-PewDiePie-Logo_0'].geometry}
        material={materials['Material.074_27']}
        position={[1.295, 0.466, -0.275]}
        rotation={[-Math.PI / 2, 0.284, Math.PI / 2]}
        scale={0.124}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013_Material094_0.geometry}
        material={materials['Material.094']}
        position={[0.83, 3.082, -2.822]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.099, 0.099, 0.049]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube088_Material098_0.geometry}
        material={materials['Material.098']}
        position={[0.99, 0.384, -0.082]}
        rotation={[-Math.PI / 2, -0.129, 0]}
        scale={[0.055, 0.049, 0.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCircle_Material104_0.geometry}
        material={materials['Material.104']}
        position={[0.877, 3.082, -2.823]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.057}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_Material055_0.geometry}
        material={materials['Material.055']}
        position={[-1.386, 2.957, 3.004]}
        rotation={[-Math.PI / 2, -0.07, Math.PI / 2]}
        scale={[3.253, 0.041, 1.841]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_Material044_0.geometry}
        material={materials['Material.044']}
        position={[-1.467, 2.637, 3.004]}
        rotation={[-Math.PI / 2, -0.122, Math.PI / 2]}
        scale={[-3.253, 0.147, 1.529]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gallerymodel_gallerymodel_0.geometry}
        material={materials['Material.074_28']}
        position={[-1.42, 1.648, 5.961]}
        rotation={[0.441, -1.284, 0.441]}
        scale={0.807}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bg2_bg2_0.geometry}
        material={materials['Material.074_29']}
        position={[-1.537, 1.949, 0.83]}
        rotation={[1.572, -1.442, 1.567]}
        scale={1.13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MY_SCREEN_MY_SCREEN_0.geometry}
        material={materials['Material.074_30']}
        position={[-1.362, 3.001, 3.004]}
        rotation={[-Math.PI / 2, 1.501, Math.PI / 2]}
        scale={[3.316, 3.481, 3.316]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['gigabyte-logo_gigabyte-logo_0'].geometry}
        material={materials['Material.074_31']}
        position={[-1.615, 4.494, 0.821]}
        rotation={[1.571, -1.501, 1.571]}
        scale={0.237}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004_Material002_0.geometry}
        material={materials['Material.002']}
        position={[-1.487, 1.81, 2.992]}
        rotation={[-Math.PI / 2, -0.07, Math.PI / 2]}
        scale={[1.676, 0.178, 1.935]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_Material003_0.geometry}
        material={materials['Material.003']}
        position={[-1.865, 2.916, 2.974]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.163, 0.288, 0.129]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006_Material043_0.geometry}
        material={materials['Material.043']}
        position={[-2.03, -0.648, 3.004]}
        rotation={[-Math.PI / 2, -0.07, Math.PI / 2]}
        scale={[0.406, 0.166, 5.316]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007_Material037_0.geometry}
        material={materials['Material.037']}
        position={[-2.13, 0.353, 2.961]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-1.938, 0.541, 0.093]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008_Material036_0.geometry}
        material={materials['Material.039']}
        position={[-0.802, 0.316, 4.531]}
        rotation={[-Math.PI / 2, 0, 1.249]}
        scale={[0.491, 1.088, 0.056]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010_Material006_0.geometry}
        material={materials['Material.006']}
        position={[-1.811, 0.316, 2.958]}
        rotation={[-Math.PI / 2, 0, 3.136]}
        scale={[0.434, 0.962, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8_Tastatur_Seite_0.geometry}
        material={materials.Tastatur_Seite}
        position={[1.477, 0.332, 4.031]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10_Tastatur_Unterseite_0.geometry}
        material={materials.Tastatur_Unterseite}
        position={[1.477, 0.332, 4.031]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14_Material004_0.geometry}
        material={materials['Material.004']}
        position={[1.477, 0.332, 4.031]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30_Material007_0.geometry}
        material={materials['Material.007']}
        position={[1.477, 0.332, 4.031]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_47_Material005_0.geometry}
        material={materials['Material.074_32']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_49_Tasten_2_0.geometry}
        material={materials.Tasten_2}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_55_Material057_0.geometry}
        material={materials['Material.074_33']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_59_Material060_0.geometry}
        material={materials['Material.074_34']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_65_Material066_0.geometry}
        material={materials['Material.074_35']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_67_Material067_0.geometry}
        material={materials['Material.074_36']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_81_Material068_0.geometry}
        material={materials['Material.074_37']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_93_Material069_0.geometry}
        material={materials['Material.074_38']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_103_Material070_0.geometry}
        material={materials['Material.074_39']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Object_782_OnTheFly-bg_0'].geometry}
        material={materials['Material.074_40']}
        position={[1.016, 0.406, 2.44]}
        rotation={[-Math.PI / 2, 0.078, Math.PI / 2]}
        scale={0.219}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_1056_Material073_0.geometry}
        material={materials['Material.073']}
        position={[1.388, 0.506, 3.958]}
        rotation={[-Math.PI / 2, 0.043, Math.PI / 2]}
        scale={0.03}
      />
    </group>
  )
}

useGLTF.preload('models/gamingdesk.glb')
export default ComputerRoom
